logging:
  file:
    path: /var/log/${spring.application.name}
  level:
    com.example: debug
    org.springframework: debug
    org.springframework.boot.autoconfigure: info

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: demo
    password: demo



